### ISSUE TITLE
Suggestion the "done" macro

### ISSUE THREAD

**Issue by Zachac** [ChapelR/custom-macros-for-sugarcube-2#11]
The "done" macro would execute its contents after the passage is done loading. A functional equivalent to the PassageDone passage or the :passagedisplay event, except exclusive to the passage it is defined in.

I had to write this myself, so here is my implementation
```javascript
Macro.add("done", {
    skipArgs: true,
    tags: null,
    handler: function () {
		var contents = this.payload[0].contents.trim()
		
		if (contents != "") {
			$(document).one(':passagedisplay', function (ev) {
			Wikifier.wikifyEval(contents)	
			})
		}
    }
})
```

Example Usage
```
<<done>>
<<if true or false>>
<<remove ".conditional">>
<</if>>
<</done>>
```

This is a useful macro because it allows the execution of [DOM Macros](http://www.motoslave.net/sugarcube/2/docs/macros.html#macrocat-dom) in the native passage. It also doesn't rely on arbitrary timing, instead it actually uses the events within sugarcube. So I think this could be a worthwhile addition.

**Comment by ChapelR** [comment]
Hmm. That's not a bad idea. I may add something similar in the future.  

Thanks for the suggestion.
