### ISSUE TITLE
No Instance Method for determining if inventory is empty

### ISSUE THREAD

**Issue by greyelf** [ChapelR/custom-macros-for-sugarcube-2#19]
There is no Instance Method equivalent of `<inventory>.inv.length === 0` which makes it hard to programatically check if an inventory is empty, unless you know about the (correctly) undocumented `<inventory>.inv` Array property.

**Comment by ChapelR** [comment]
Thanks for letting me know about these issues. Once I get an update together I'll let the user on the Q&A know.
