### ISSUE TITLE
Simple Inventory Containers Bug

### ISSUE THREAD

**Issue by AccreditedDesign** [ChapelR/custom-macros-for-sugarcube-2#2]
Hi Chapel, thanks again for your work on this. There is a problem (i believe, unless I'm missing something) with both `<<container>>` and `<<setcontainer>><<droplist>>`.
Here is my basic setup:

```
::StoryInit
TAGS: skip
<<placeat 'Flower Pot' 'Cabin Key'>>

::StoryMenu
TAGS: menu
[[Inventory]]

::Inventory
TAGS: menu
!!Inventory
<<setcontainer>><<droplist>>
<<return>>

::Flower Pot
TAGS: NONE
<<has 'Cabin Key'>>\
You have already taken the key.
<<otherwise>>
You tip the flower pot on it's side to reveal the Cabin key!
<</has>>
<b>You See:</b> <<container>>
```

When the Cabin Key is picked up, it is visible in inventory and everything works fine. However when the item is dropped from inside the inventory `<<droplist>>`, it is in fact dropped but does not again appear in `::Flower Pot`.
For testing, I placed the following in both `::Inventory` and `::Flower Pot`:

```
<b>You See:</b> <<container>>
<<placelist>>
```

After dropping the item, `<<container>>` and `<<placelist>>` showed nothing in `::Flower Pot`, however in `::Inventory`, `<<container>>` showed nothing, but `<<placelist>>` showed the item present in `::Inventory`
So, something with `<<setcontainer>><<droplist>>` in `::Inventory` is not returning items to the previous passage, in my case `::Flower Pot`. Further, `<<container>>` was not showing the item during the error, but `<<placelist>>` was.
Obviously you wouldn't normally want `<<container>>` or `<<placelist>>` in an Inventory Menu setup but did it to test where the items were disappearing off to.
Also of note is that I have several passages before you get to `::Flower Pot` all tagged with skip.

**Comment by ChapelR** [comment]
Thanks for the report. I'll check this out as soon as I can. 

Edit:
@AccreditedDesign 
I'm having trouble recreating the issue from the provided code; from a minimal test case, this code worked fine.  Would you mind posting and linking the project file/compiled HTML/Twine archive file or, if you can't, can you post more of your code?

**Comment by AccreditedDesign** [comment]
Here you go Chapel:
https://goo.gl/zEddKh
It's a boiled-down version of my story with the key elements. I've just realized something! In testing again, if I:
Go to Flower Pot, pick up the Cabin Key and then **_immediately_** go to inventory and drop the Cabin Key and hit return, the Cabin Key is back and available to be picked up in the passage.
This is what I did before posting the "Issue", and the issue still exists:
Go to Flower Pot, pick up the Cabin Key and now click return, which takes you to "Outside The Old Cabin". Now click Inventory and click drop and then click your way through to return to the Flower Pot passage and there's no item, and it's also no longer in inventory.
I assumed that the system would drop the item to the last passage visited without one of the skip tags, which in this case would be the Flower Pot. Instead it's effectively gone from that instance of the game. Am I misunderstanding the intent of the code, or not using a macro I should be to avoid this?

**Comment by ChapelR** [comment]
Ooooooooooh. That's not how I wrote the code to work, but that's probably how I should have written the code to work. I'll post an update soon. 

I'll make an option that allows you to either force `<<setcontainer>>` to the last viable passage or allows you to disable dropping if that passage is a certain number of turns away (i.e. 'You can't drop items here.') because in some games having dropped items piped to specific locations could be confusing for players.

**Comment by ChapelR** [comment]
I'm going to close this for now as the problem should be fixed, but I'll be testing it a bit more over the next day or two.  Let me know if it isn't working the way it ought to, and thanks for pointing this out to me.
