### ISSUE TITLE
Simple Inventory: item metadata

### ISSUE THREAD

**Issue by ChapelR** [ChapelR/custom-macros-for-sugarcube-2#22]
Items should accept metadata, which will be assigned internally: the private array will be an array of objects rather than strings. 

Each item will have: 
- name: the name of the item, as passed in. 
- stack: how many items are the same item, allowing inventories to optionally treat items as stackables (configured on a per inventory basis, probably via a new macro). 
- acquired: the name of the passage the item was acquired from. (should transfers track the giving inventory? I don't know if there's a good way to track that, since inventories are just stored in vars) 

Users will also be able to define (non-statefully) items via a new API and macro set. 

Items have: 
- name: a unique name. (required)
- tags: meta data tags for the item. 
- label: a short description of the item. (optional)
- description: a passage name or string description of the item. If the description is a passage name, that always wins out. (optional)
- onUse: wiki code or function to run on usage. (optional)
- onGet: wiki code or function to run when the item is received. (optional)
- onDrop: wiki code or function to run when the item is dropped. (optional)
- maxStack: the maximum number of items of this kind that can be carried at once. (optional)
- metadata: object for any user data. Does not need to be serializable, so functions and weird classes are fine. Only available via JS API. 

If an item is passed to an inventory that doesn't have an item def, it will be treated like a key item, per the current implementation of SI, plus the new automatic metadata properties. 

Items will probably be a class, the metadata passed into the inventory will probably include the whole instance. Might be better as a straight up factory, though. 

These additions *shouldn't* be breaking, if implemented properly, but the code will be heavier, so it may be worth adding the hooks for this system to Simple Inventory, but making the Item class and API / macros an optional extension.     

Design goals. 

- No breaking changes, this shouldn't be a 3.0.0 update if at all possible. 
- I want to preserve the simple inventory as a place users can set flags or traits. 
- I **do not** want users to use this as a poor man's attribute system, eg using a stack of "strength" items as an attribute score. I can't stop that, but I want to encourage this being used for *items*.

**Comment by virtualghost** [comment]
I don't know if it's the right place to report it, but here you go.
On your macro's description here
https://github.com/ChapelR/custom-macros-for-sugarcube-2/blob/master/docs/simple-inventory.md

`@@#link;
<<link 'Pick up the gun.'>>
	<<if $playerInventory.has('a gun')>>
		<<replace '#links'>>You already have a gun, you don't need another...<</replace>>
	<<else>>
		<<pickup '$playerInventory' 'a gun'>>
		<<replace '#links'>>You take the gun and hide it in your coat.<</replace>>
	<</if>>
<</link>>
@@`

it should be <<replace '#link'>> in the usage example, otherwise it will output an error due to it not finding #links.

**Comment by ChapelR** [comment]
UInv does this, I don't see any reason to reinvent the wheel.
