### ISSUE TITLE
No Fading Macro on the Download utility page

### ISSUE THREAD

**Issue by nopivnick** [ChapelR/custom-macros-for-sugarcube-2#29]
the [Download utility page](https://twinelab.net/custom-macros-for-sugarcube-2/download/) doesn't appear to include a selection for the Fading Macro.

**Comment by ChapelR** [comment]
Thank you. I'll fix this and the other issue and look things over for other issues.

**Comment by ChapelR** [comment]
This should be fixed now, along with the first macro issue. Thanks again.
