### ISSUE TITLE
<<event>> should use a namespace and offer a single-use option

### ISSUE THREAD

**Issue by tmedwards** [ChapelR/custom-macros-for-sugarcube-2#39]
Pretty much what it says on the tin.  It would be good if the `<<event>>` macro:

* Used a namespace for its handlers.
* And, if possible, offered an option to make the handler single-use.

**Comment by ChapelR** [comment]
I have memories of making a `once` option. I guess I didn't, or it never made it into the actual repo. Either way, it's a good idea, and so is namespacing things.
