### ISSUE TITLE
Wrong examples in articles.md

### ISSUE THREAD

**Issue by samplereality** [ChapelR/custom-macros-for-sugarcube-2#41]
In the docs for the articles macro: under the setup.articles.output() section, all the examples use setup.articles.find().

For example, the example reads
`setup.articles.find('UFO'); // 'a UFO'`

But it should be

`setup.articles.output('UFO'); // 'a UFO'`

**Comment by ChapelR** [comment]
Whoops. 

Anyway, thanks for opening this. I'll fix this in the next version.
