### ISSUE TITLE
`<<disable>>` macro

### ISSUE THREAD

**Issue by ChapelR** [ChapelR/custom-macros-for-sugarcube-2#42]
https://github.com/tmedwards/sugarcube-2/issues/46

**Comment by tmedwards** [comment]
I'd suggest using [`<jQuery>.ariaDisabled()`](http://www.motoslave.net/sugarcube/2/docs/#methods-jquery-prototype-method-ariadisabled) ([see code](https://github.com/tmedwards/sugarcube-2/blob/master/src/lib/jquery-plugins.js#L169)) and [`<jQuery>.ariaIsDisabled()`](http://www.motoslave.net/sugarcube/2/docs/#methods-jquery-prototype-method-ariaisdisabled) ([see code](https://github.com/tmedwards/sugarcube-2/blob/master/src/lib/jquery-plugins.js#L222)).  They should serve all elements handled by your current code, and more, while also setting the appropriate ARIA content attributes.

**Comment by ChapelR** [comment]
Sounds good.
