### ISSUE TITLE
Add touch support for typesim macro?

### ISSUE THREAD

**Issue by Gamewise** [ChapelR/custom-macros-for-sugarcube-2#45]
As a suggestion - (feel free to ignore!), it'd be cool if the typesim macro included support for ipads.
It's such a fun little effect! :)

**Comment by ChapelR** [comment]
I can look into this, but in general mobiles' virtual keyboards don't trigger the same kind of events as physical keyboards, so I'm not sure how I could approach it. Probably the best I could do is just make it so tapping on the element fills it out one letter at a time on mobile devices.

**Comment by Gamewise** [comment]
Oooh yep I see that is tricky then. I think tapping on the element would be
just fine tbh, but yeah if it's too annoying or whatever don't worry about
it!

**Comment by ChapelR** [comment]
added in v2.9.0

**Comment by Gamewise** [comment]
Ah wow awesome!!!!!

**Comment by ChapelR** [comment]
Sorry about the wait.

**Comment by Gamewise** [comment]
No not at all! I'm just stoked you got around to it! Thanks so much for all
you do.
