### ISSUE TITLE
small issue with cycle macro

### ISSUE THREAD

**Issue by dev-utopix** [ChapelR/custom-macros-for-sugarcube-2#46]
Hello, first of all I have to thanks you for the huge effort and the awesome tool your marcros are, the documentation it's extensive and very well done.
I'm trying to use the Cycle Events code explained in the documentation placing it in the Javascript section of my Twine 2 story with the latest version of Sugarcube and it doesn't seems to work. Have used a lot of your macros and everything else works like a charm, keep the amazing job!

**Comment by ChapelR** [comment]
Thanks, I'll look into it.

**Comment by ChapelR** [comment]
There was indeed an error in the code, the events should now work. Thanks again for the heads-up.
