### ISSUE TITLE
Enhance The Speech Box System

### ISSUE THREAD

**Issue by Muderru** [ChapelR/custom-macros-for-sugarcube-2#48]
Is it possible to change the macro this way? 
`<<character macrosname name imageSrc>>`
For example, <<character 'lisa' 'Лиза' 'images/portraits/lisa.jpg'>>

**Comment by ChapelR** [comment]
See PR #47 

Yes, Gwen actually already added this feature for me, I just have to pull it and make a release. I've been extremely busy but I hope to get to it this week. If you can't wait, you can grab the code from Gwen's fork. I haven't completely tested it yet, but I'm sure it works as advertised.

**Comment by Muderru** [comment]
Oh, thank you very much.

**Comment by ChapelR** [comment]
This has been added in the latest update, if you still need it.
