### ISSUE TITLE
Speech box styles

### ISSUE THREAD

**Issue by tmedwards** [ChapelR/custom-macros-for-sugarcube-2#58]
It might be a good idea to use child selectors on the `.say` children to avoid selecting descendant elements.  E.g.,

```css
.say > img {
.say > p:first-of-type {
.say > p:last-of-type {
```

----

https://github.com/ChapelR/custom-macros-for-sugarcube-2/blob/3bdbdfbe5ae47a46e4f4e52766d78701939ae9a6/scripts/speech.css#L6
https://github.com/ChapelR/custom-macros-for-sugarcube-2/blob/3bdbdfbe5ae47a46e4f4e52766d78701939ae9a6/scripts/speech.css#L12
https://github.com/ChapelR/custom-macros-for-sugarcube-2/blob/3bdbdfbe5ae47a46e4f4e52766d78701939ae9a6/scripts/speech.css#L18

**Comment by ChapelR** [comment]
Good idea. Thanks.
