### ISSUE TITLE
Ui Macro hinders css @import

### ISSUE THREAD

**Issue by Amathele** [ChapelR/custom-macros-for-sugarcube-2#62]
I have implemented the UI-Macro to get rid of the Menu bar, but since then my fonts that are hosted on fronts.googleapi.com are not working anymore.

**Comment by ChapelR** [comment]
The UI macro will not have any impact on your CSS.

**Comment by Amathele** [comment]
Yes, you are right. Something else broke, i guess I copied the code without a semicolon or something.

Sorry.

**Comment by ChapelR** [comment]
No problem, glad you were able to figure it out.
