### ISSUE TITLE
URL for Simple Inventory 3 library has an additional forward slash in it

### ISSUE THREAD

**Issue by greyelf** [ChapelR/custom-macros-for-sugarcube-2#68]
As it says in the title, there is an additional forward slash in the library's new URL, just before the **`#`** wild card.

eg. new URL is `https://twinelab.net/simple-inventory//#/` and it likely should be `https://twinelab.net/simple-inventory/#/`, which is the structure of the HAL and Macro Collection URLs.

**Comment by ChapelR** [comment]
Thanks. I think I messed something up in my domain configuration actually. I'll try to fix it.

**Comment by ChapelR** [comment]
Should be fixed.
