### ISSUE TITLE
scripts/playtime.js

### ISSUE THREAD

**Issue by tmedwards** [ChapelR/custom-macros-for-sugarcube-2#8]
### [Line 52](https://github.com/ChapelR/custom-macros-for-sugarcube-2/blob/95cbcd910d7de1c5c737159b7e785eee17850900/scripts/playtime.js#L52) ###

```
setup.playTime.get = function (m) {
	var ms   = setup.playTime.getMS();
	var time = setup.playTime.getTimeArray(ms);
	if (['h', 'hr', 'hrs', 'hour', 'hours'].includes(m)) {
		return time[2];
	} else if (['min', 'mins', 'minutes', 'minute', 'm'].includes(m)) {
		return time[1];
	} else if (['s', 'second', 'sec', 'seconds', 'secs'].includes(m)) {
		return time[0];
	}
	return ms;
};
```

Would be marginally better as:

```
var hourNames = ['h', 'hr', 'hrs', 'hour', 'hours'];
var minNames  = ['m', 'min', 'mins', 'minute', 'minutes'];
var secNames  = ['s', 'sec', 'secs', 'second', 'seconds'];
setup.playTime.get = function (m) {
	var ms   = setup.playTime.getMS();
	var time = setup.playTime.getTimeArray(ms);
	if (hourNames.includes(m)) {
		return time[2];
	}
	if (minNames.includes(m)) {
		return time[1];
	}
	if (secNames.includes(m)) {
		return time[0];
	}
	return ms;
};
```

Or, since you don't have an ID for milliseconds, the lazier:

```
setup.playTime.get = function (m) {
	var ms   = setup.playTime.getMS();
	var time = setup.playTime.getTimeArray(ms);
	switch (m[0]) {
	case 'h': return time[2];
	case 'm': return time[1];
	case 's': return time[0];
	}
	return ms;
};
```

### [Line 116](https://github.com/ChapelR/custom-macros-for-sugarcube-2/blob/95cbcd910d7de1c5c737159b7e785eee17850900/scripts/playtime.js#L116) ###

```
		var arr = (function (args) {
			var ret = [];
			args.forEach( function (a) {
				a = a + '';
				ret.push(a.trim().toLowerCase());
			});
			return ret;
		}(this.args)),
```

Would be better written using the [`<Array>.map()` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map):

```
		var arr = this.args.map(function (arg) {
			return String(arg).trim().toLowerCase();
		}),
```

### [Line 126](https://github.com/ChapelR/custom-macros-for-sugarcube-2/blob/95cbcd910d7de1c5c737159b7e785eee17850900/scripts/playtime.js#L126) ###

```
	fmt = (arr.includesAny(['format', 'f', 'fmt', 'b', 'bold', 'true'])) ? true : false,
```

Would be better written without the ternary/conditional operator because the [`<Array>.includesAny()` method](http://www.motoslave.net/sugarcube/2/docs/object-methods.html#array-arrayprotoincludesany) already returns a boolean:

```
	fmt = arr.includesAny(['format', 'f', 'fmt', 'b', 'bold', 'true']),
```

**Comment by ChapelR** [comment]
Merged, thanks.

Question:
```javascript
var hourNames = ['h', 'hr', 'hrs', 'hour', 'hours'];
var minNames  = ['m', 'min', 'mins', 'minute', 'minutes'];
var secNames  = ['s', 'sec', 'secs', 'second', 'seconds'];
setup.playTime.get = function (m) {
	var ms   = setup.playTime.getMS();
	var time = setup.playTime.getTimeArray(ms);
	if (hourNames.includes(m)) {
		return time[2];
	}
	if (minNames.includes(m)) {
		return time[1];
	}
	if (secNames.includes(m)) {
		return time[0];
	}
	return ms;
};
```
Is this creating autoglobals?  my knee jerk is to want to place the var statements inside the `setup.playTime.get` function, but I'm not 100% sure that's required?  Or maybe the whole thing should be in an IIFE to prevent leaks to the global scope?  I might also be missing something.

**Comment by tmedwards** [comment]
No.  The `var` statements outside of the function there do not create auto-globals—they wouldn't even within the global scope, which they shouldn't be anyway, since most script evaluation within SugarCube happens within its own scope.  If you did somehow evaluate the `var` statements within the global scope, then you'd create normal globals.

Auto-globals are created in two ways only:

1. Assigning to `window`—e.g. `window.whatTheWhatNow = function () {};`.
2. Assigning to a non-existent identifier while not running in strict mode—e.g. `whatTheWhatNow = function () {};`.

SugarCube itself, and thus all code evaluated within its scope, runs in strict mode, so the latter would be a reference error—e.g. *assignment to undeclared variable whatTheWhatNow*—unless you slipped the leash.


The reason I moved the `var` statements out of the function is by putting them within it you're recreating those, effectively static, arrays each and every time it's called.  It's not a lot of overhead, but something you certainly don't need to be doing.  Assuming people put the code into Story JavaScript/`script`-tagged passages, having them within the temporary localized scope that they're evaluated within hurts nothing at all.

Yes, you could wrap the `var` statements and function within an IIFE, but that's overkill in all honesty.  I've been trying to break myself of that habit.

If you did want to use an IIFE to isolate the code, then I'd suggest wrapping each module as a whole in one.  That would be a much better use of an IIFE.
